# Generated by Django 4.2.16 on 2024-10-15 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bankaccount_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='currency',
            field=models.CharField(default='NIS', max_length=3),
        ),
    ]
