# Generated by Django 4.2.16 on 2024-10-16 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_bank'),
    ]

    operations = [
    ]
