# Generated by Django 4.2.16 on 2024-10-16 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_create_initial_bank'),
    ]

    operations = [
    ]
