# Generated by Django 4.2.16 on 2024-10-16 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_create_initial_bank'),
    ]

    operations = [
    ]
