# Generated by Django 4.2.16 on 2024-10-16 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_create_initial_bank'),
    ]

    operations = [
    ]
