# Generated by Django 4.2.16 on 2024-10-16 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_bankaccount_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankaccount',
            name='unique_user_account',
        ),
    ]
