# Generated by Django 4.2.16 on 2024-10-16 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_remove_bankaccount_unique_user_account'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user',
        ),
    ]
