# Generated by Django 4.2.16 on 2024-10-16 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_bankaccount_user_alter_user_id'),
    ]

    operations = [
    ]
