# Generated by Django 4.2.16 on 2024-10-16 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_create_initial_bank'),
    ]

    operations = [
    ]
