# Generated by Django 4.2.16 on 2024-10-16 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_bankaccount_user'),
    ]

    operations = [
    ]
