# Generated by Django 4.2.16 on 2024-10-18 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_bankaccount_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='currency',
            field=models.CharField(choices=[('NIS', 'New Israeli Shekel'), ('USD', 'US Dollar'), ('EUR', 'Euro')], default='NIS', max_length=3),
        ),
    ]
