# Generated by Django 4.2.16 on 2024-10-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='original_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='original_currency',
            field=models.CharField(default='NIS', max_length=3),
        ),
    ]
