# Generated by Django 4.2.16 on 2024-10-21 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_transaction_original_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccount',
            name='is_suspended',
        ),
    ]
