# Generated by Django 4.2.16 on 2024-10-25 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_remove_bankaccount_is_suspended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='original_currency',
            new_name='currency',
        ),
    ]
